services:
  neo4j:
    image: neo4j:5.18.1-community-bullseye
    environment:
      NEO4J_AUTH: "none"
      NEO4JLABS_PLUGINS: '["graph-data-science"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-test:/data

volumes:
  neo4j-test:
    external: true
