version: "3.7"
services:
  web:
    image: creativefeather/sapper
    stdin_open: true
    tty: true
    environment:
      HOST: "0.0.0.0"
    networks:
      - backend
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ".:/home/node/app"

networks:
  backend: