#!/bin/bash

if [ $(ls -A | wc -l) -eq 0 ]
then
  npx degit sveltejs/template
  npm install
  npm install --save-dev chokidar

  # mv README.md
  mv $APP_FILES_DEST/EXTRA_SETUP.md $APP_DIR/EXTRA_SETUP.md
  mv $APP_FILES_DEST/docker-compose.svelte.yml $APP_DIR/docker-compose.yml
  mv $APP_FILES_DEST/docker-compose.override.svelte.yml $APP_DIR/docker-compose.override.yml

  rm -rf $APP_FILES_DEST
else
  npm run dev
fi