services:
  # springboot-app:
  #   image: springboot-angular:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     SPRING_DATASOURCE_URL: ${DATASOURCE_URL}      #jdbc:mysql://mysql:3306/testdb
  #     SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
  #     SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
  #   depends_on:
  #     db:
  #       condition: service_healthy

  db:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - mysql_password
    # volumes:
    #   - mysql-data:/var/lib/mysql

secrets:
  mysql_root_password:
    external: true
  mysql_database:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true
volumes:
  mysql-data:

